### ISSUE TITLE
UBY: jp-private-code-span-padding is tough to read with a yellow bg

### ISSUE THREAD

**Issue by westurner** [timkpaine/jupyterlab_miami_nights#71]
**Describe the bug**
In Python notebooks, AssertionError traceback lines appear to be highlighted with the `jp-private-code-span-padding` var set to `.ansi-yellow-bg { background-color: #ddb62b; }`; which  is tough to read with the text color at `color: var(--neon-night-purple0);`.

IDK what would look good and have good UX by comparison:

Status quo:
- background-color: bright yellow
- color: neon purple

Suggestionso:
- bg/color

**Screenshots**
![Screenshot from 2024-02-10 16-41-15](https://github.com/timkpaine/jupyterlab_miami_nights/assets/50891/d6aadaf5-c773-442e-b161-866cd7e553d2)

**Comment by timkpaine** [comment]
Hey agreed, im going to tweak this to be better

**Comment by westurner** [comment]
One idea:
```css
.jp-RenderedText pre .ansi-yellow-bg {
  background-color: #2a262b;
}

/*
Also, rough ideas for fixing pygments syntax highlighting:

pygments > function_method_name {
  color: rgb(128,128,255);
}

pygments > strings,docstrings {
  // color: rgb(175,0,0) ; 
  color: rgb(232,48,48);
}

- https://nbconvert.readthedocs.io/en/latest/highlighting.html#making-your-own-styles
- 
*/

```
